- name: Deploy frontend application on Kubernetes
  hosts: k8smaster
  gather_facts: false
  become: yes
  tasks:
    - name: Create deployment
      k8s:
        kubeconfig: "~/.kube/config"
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: frontend-khaled
            namespace: default
            labels:
              app: frontend-khaled
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: frontend-khaled
            template:
              metadata:
                labels:
                  app: frontend-khaled
              spec:
                containers:
                  - name: frontend-khaled
                    image: walabr/frontend-khaled:prod
                    ports:
                      - containerPort: 3000
              # nodeSelector:
               #      kubernetes.io/hostname: worker1      
        # context: "kubernetes-admin@kubernetes"
        # api_key: "kubeconfig-user-tz4cgnc87h:c5bblz84ddpxbmbnr9wf6fn5n4rw8k8xdn4t4wjgwcj7xq9fzxprsg"
       # verify_ssl: false

    - name: Create service
      k8s:
        state: present
        kubeconfig: "~/.kube/config"
        verify_ssl: no
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: frontend-khaled
            namespace: default
            labels:
              app: frontend-khaled
          spec:
            selector:
              app: frontend-khaled
            ports:
              - protocol: TCP
                port: 80
                targetPort: 3000
            type: LoadBalancer
